# Generated by Django 5.1.3 on 2024-12-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('meta_horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='habit',
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('horas_registradas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='Habitos.habitos')),
            ],
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
