# Generated by Django 5.1.3 on 2024-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0002_habitos_remove_progress_habit_progreso_delete_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habitos',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
