# Generated by Django 5.1.3 on 2024-12-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0004_remove_habitos_meta_horas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='tiempo_registrado',
        ),
        migrations.AddField(
            model_name='progreso',
            name='horas_registradas',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progreso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='habito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_set', to='Habitos.habitos'),
        ),
    ]
