# Generated by Django 5.1.3 on 2024-12-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0005_remove_progreso_tiempo_registrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_transcurrido', models.PositiveIntegerField(default=0, help_text='Tiempo registrado en minutos')),
                ('completado', models.BooleanField(default=False)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Habitos.habitos')),
            ],
        ),
    ]
