# Generated by Django 5.1.3 on 2024-12-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0007_habitos_progreso_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitos',
            name='progreso_objetivo',
        ),
    ]
