# Generated by Django 5.1.3 on 2024-12-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0008_remove_habitos_progreso_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitos',
            name='prioridad',
            field=models.CharField(max_length=10),
        ),
    ]
