# Generated by Django 5.1.3 on 2024-12-25 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitos', '0009_alter_habitos_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohabito',
            name='habito',
        ),
        migrations.CreateModel(
            name='RegistroInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_transcurrido', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Habitos.habitos')),
            ],
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
        migrations.DeleteModel(
            name='RegistroHabito',
        ),
    ]
